name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: script.test
      id: script-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: script.test
        setup-command: npm install
        command: npm test
        timeout: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SCRIPT-TEST_RESULTS: "${{steps.script-test.outputs.result}}"
      with:
        runners: script-test
